### ISSUE TITLE
[FEATURE] return `continent` for the geocoded results

### ISSUE THREAD

**Issue by elgandoz** [maptiler/maptiler-geocoding-control#10]
**Is your feature request related to a problem? Please describe.**
When I geocode a point, I also need to obtain the `continent` `[Asia|Africa|North America|South America|Antarctica|Europe|Oceania]`

**Describe the solution you'd like**
Add `continent` to the returned results and to the `type` filter.

**Describe alternatives you've considered**
Search within a custom built array of countries-continents pair or double geocode the point or country with another service (😥)

**Additional context**
_Oceania_ has a sort of blurred definition in some countries.
There could be some inconsistencies for certain countries with overseas territories (Spain's Ceuta, French Polynesia and many similar cases).
These are more of edge cases, and like with the regular geocoding, a standard needs to be found.
https://en.wikipedia.org/wiki/Continent

**Comment by zdila** [comment]
We have introduced `continental_marine` index which includes continents, oceans and seas.
