### ISSUE TITLE
[BUG] Type incompatibility between this lib `Map` type and @maptiler/sdk `Map` type

### ISSUE THREAD

**Issue by toniopelo** [maptiler/maptiler-geocoding-control#13]
**Describe the bug**
This title says it all, here is a screenshot of the exact error:
![image](https://github.com/maptiler/maptiler-geocoding-control/assets/9287511/df894401-a1b8-47bb-aece-2b382321f381)

**To Reproduce**
Just follow the readme of this package.

**Expected behavior**
No type error.

**Additional context**
All packages are on their latest version.

**Comment by zdila** [comment]
Which version of `@maptiler/geocoding-control` and `@maptiler/sdk` are you using? With the latest versions (0.0.99 and 1.1.2) I can't reproduce the problem. Also please provide your sample code.

**Comment by zdila** [comment]
Please reopen with more details if you can reproduce it again. Thank you.
