### ISSUE TITLE
[BUG] geocoding control component freezes after first search

### ISSUE THREAD

**Issue by Robinlovelace** [maptiler/maptiler-geocoding-control#16]
**Describe the bug**

I have followed the tutorial at    and the geocoding control component works great, but only on the first go.

**To Reproduce**

See reproducible example + video associated with a simple codebase showing this behaviour here https://github.com/cruse-bike/cruse/issues/8

**Expected behavior**

I was expecting to be able to clear the search results and fly to another place after the first 'flyto'.

**Screenshots**

https://github.com/maptiler/maptiler-geocoding-control/assets/1825120/735aa8ab-932f-477b-902d-4dbe80cd3374

**Additional context**

I'm experimenting with MapLibre and Svelte to add quality of life features (like geocoding) and UX improvements to this web application funded by the Irish Government for sustainable transport planning: https://cruse.bike/

**Comment by Robinlovelace** [comment]
I should add: I'm not 100% sure this is a bug and I'm a Svelte novice so possible that I've made a silly mistake, apologies if so, but thought it may be helpful to report this unexpected behaviour.

**Comment by zdila** [comment]
Hi @Robinlovelace .

Than you for your report!

Would you be so kind and try to provide us a minimal reproducible example? You can attach a tarball or create one from https://codesandbox.io/p/sandbox/svelte-geocoding-control-4dzp2r (provide your API key for it to work).

**Comment by zdila** [comment]
I have tried it with your project but I can't reproduce it. Using latest Vivaldi on Linux.

Do you see any errors in JS console?

**Comment by Robinlovelace** [comment]
> I have tried it with your project but I can't reproduce it. Using latest Vivaldi on Linux.
> 
> Do you see any errors in JS console?

Thanks for testing. Just to check did you remove this line before trying to reproduce it?

As far as I recall this magic line is not in the docs:

```
+			if (!e.detail?.center) return;
```

**Comment by Robinlovelace** [comment]
OK glad to you can reproduce the issue. I've taken a look at the API reference and it's not immediately clear that  

```
+			if (!e.detail?.center) return;
```

needs to be added to the geocoding control to prevent the issue. Maybe worth flagging in the documentation?

I'm not a JavaScript developer so it's possible that patch is obvious to others, may be worth getting feedback from @mattlehr who provided the patch in https://github.com/cruse-bike/cruse/pull/9, could this be better documented or was it fairly clear this was needed?

**Comment by Robinlovelace** [comment]
I was referring to this documentation: https://docs.maptiler.com/svelte/maplibre-gl-js/geocoding-control/

Is the equivalent bit this?

```
  {#if mapController}
```

I'll defer to others on whether this is an issue with the documentation/implementation or whether I just need to improve my JS knowhow which is entirely feasible.

**Comment by Robinlovelace** [comment]
One additional question: how should this be debugged? I found it a confusing error message but again that's likely because I'm JS novice.

**Comment by zdila** [comment]
> I was referring to this documentation: https://docs.maptiler.com/svelte/maplibre-gl-js/geocoding-control/

That sample doesn't use `on:select` or other advanced features.

> what's the best way to debug this kind of error? I found it a confusing error message but again that's likely because I'm JS novice

Your browser's DevTools should show such errors in the Console:

![2023-11-30_21-21](https://github.com/maptiler/maptiler-geocoding-control/assets/636095/1d3770c3-1bd9-4b73-9eab-ca923f8eda68)

**Comment by Robinlovelace** [comment]
Sounds like working as intended then, nothing to change? Happy for this to be closed and thanks for all the responses.
