### ISSUE TITLE
[BUG] Clearing features when the map style switches conflicts with svelte-maplibre

### ISSUE THREAD

**Issue by dabreegster** [maptiler/maptiler-geocoding-control#59]
**Describe the bug**
https://github.com/dimfeld/svelte-maplibre/ is a very useful Svelte wrapper for maplibre. It has some code for preserving existing sources and layers when the basemap style changes: https://github.com/dimfeld/svelte-maplibre/blob/d7697024d187c9e94504f8220a8b19fbc4ecd055/src/lib/MapLibre.svelte#L266. Unfortunately, #30 breaks in combination with this.

**To Reproduce**
I can make a minimal repo if absolutely necessary, but here it is in a real app:
1) Clone https://github.com/acteng/atip
2) Edit `package.json` and use the latest package, `"@maptiler/geocoding-control": "^1.4.1"`
3) `npm i` and `npm run setup-govuk`
4) `npm run dev`
5) Go to http://localhost:5173/browse.html
6) Enable any layer on the left hand side; it should appear on the map
7) Switch the basemap at the very bottom
8) The layer should still be visible, but it won't  be. The console will show `MapLibre error: Error: Source "full-geom" already exists.` and something like ` MapLibre error: Error: Cannot style non-existing layer "trams".`

**Expected behavior**
In the above instructions, for step 8, the layers should continue working after changing basemap styles.

**Additional context**
How about a new boolean option `handleStyleUpdates` defaulting to true? I need to try it out, but I think then the change would simply be:

```
  map.on("styledata", () => {
    if (handleStyleUpdates) { 
      addFullGeometryLayer();
   }
  });
```

If this approach sounds OK, I can try it out with my local setup and send a PR. Thanks!

**Comment by dabreegster** [comment]
Thanks so much for implementing a fix here! Could I also request a new npm release please? I'm having vite config issues trying to pin to GH directly.

**Comment by zdila** [comment]
@dabreegster meanwhile released. Please try.
