### ISSUE TITLE
[BUG] Icons not loading in search results

### ISSUE THREAD

**Issue by fischja** [maptiler/maptiler-geocoding-control#6]
**Describe the bug**
The icons associated with search results do not load. Instead, a placeholder text is shown.

**To Reproduce**
Error occurs on this demo page (and in my app) (firefox and chrome): https://docs.maptiler.com/sdk-js/examples/geocoder-component/  
Works fine on this demo page: https://www.maptiler.com/cloud/geocoding/

**Screenshots**
![image](https://github.com/maptiler/maptiler-geocoding-control/assets/23638305/952a0d9f-bfbd-4c9c-8e17-2b7e906c814a)

![image](https://github.com/maptiler/maptiler-geocoding-control/assets/23638305/88d4dd69-f61e-408a-86b3-1dba119876b0)

Is it possible to disable icons completely (appropriate for my use case)? I did not find such a parameter option.

**Comment by zdila** [comment]
Fixed in 3899ef7 and published. Thanks for the report!
